spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/wordle
spring.datasource.username=wordle_app
spring.datasource.password=${WORDLE_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
